# Generated by Django 3.2 on 2021-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('amount', models.FloatField(default=1)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('date', models.DateField()),
            ],
        ),
    ]
